In [18]:
import syft as sy
import numpy as np

In [19]:
domain = sy.login(email="info@openmined.org", password="changethis", port=8081)


Anyone can login as an admin to your node right now because your password is still the default PySyft username and password!!!

Connecting to localhost... done! 	 Logging into canada... done!


In [20]:
domain.datasets.purge(skip_check=True)

In [21]:
if len(domain.datasets) == 0:
    data = np.random.random((5, 5))
    gt_dsa = np.random.choice(["Bob", "Billy", "Brandon"], (5, 5))
    pt_dsa = np.random.choice(["Joe"], (5, 5))
    gamma_tensor = sy.Tensor(data).private(min_val=0, max_val=1, data_subjects=gt_dsa)
    phi_tensor = sy.Tensor(data).private(min_val=0, max_val=1, data_subjects=pt_dsa)

    domain.load_dataset(
        assets={
            "phi": phi_tensor, 
            "gamma": gamma_tensor
        }, 
        name="Test dataset", 
        description="Descr."
    )
else:
    domain.datasets

Loading dataset... uploading...🚀                                                                                                                                             

Uploading `gamma`: 100%|█████████████████████████████████████████████| 1/1 [00:00<00:00, 137.50it/s]

Dataset is uploaded successfully !!! 🎉

Run `<your client variable>.datasets` to see your new dataset loaded into your machine!


In [22]:
phi = domain.datasets[-1]["phi"]

In [23]:
data = phi.get_copy().child

In [24]:
data.trace()

PhiTensor(child=2.8021591494767066, min_vals=<lazyrepeatarray data: [0.] -> shape: ()>, max_vals=<lazyrepeatarray data: [5.] -> shape: ()>)

In [25]:
res = phi.trace()

In [26]:
res.get_copy()

Tensor(child=PhiTensor(child=2.8021591494767066, min_vals=<lazyrepeatarray data: [0.] -> shape: ()>, max_vals=<lazyrepeatarray data: [5.] -> shape: ()>))

In [27]:
res.get_copy()

Tensor(child=PhiTensor(child=2.8021591494767066, min_vals=<lazyrepeatarray data: [0.] -> shape: ()>, max_vals=<lazyrepeatarray data: [5.] -> shape: ()>))

In [12]:
phi_res = phi.get_copy()
print(phi_res.child.child, phi_res.child.data_subjects.sum(), phi_res.child.min_vals, phi_res.child.max_vals)

[[0.5808899  0.6610832  0.84622848 0.98620149 0.16347447]
 [0.83961905 0.19573528 0.85469873 0.67341633 0.27540538]
 [0.72422293 0.35704406 0.94523301 0.48327048 0.80650038]
 [0.10703216 0.00424864 0.92663971 0.52008441 0.50657996]
 [0.88296833 0.90654247 0.48253977 0.09829327 0.4685918 ]] DataSubjectArray: {'Joe'} <lazyrepeatarray data: [0] -> shape: (5, 5)> <lazyrepeatarray data: [1] -> shape: (5, 5)>


In [13]:
gamma = domain.datasets[-1]["gamma"]

In [14]:
data = gamma.get_copy().child

In [15]:
local_res = data.copy()
print(local_res.child)
print(local_res.min_vals)
print(local_res.max_vals)

[[0.5808899  0.6610832  0.84622848 0.98620149 0.16347447]
 [0.83961905 0.19573528 0.85469873 0.67341633 0.27540538]
 [0.72422293 0.35704406 0.94523301 0.48327048 0.80650038]
 [0.10703216 0.00424864 0.92663971 0.52008441 0.50657996]
 [0.88296833 0.90654247 0.48253977 0.09829327 0.4685918 ]]
<lazyrepeatarray data: [0] -> shape: (5, 5)>
<lazyrepeatarray data: [1] -> shape: (5, 5)>


In [16]:
res = gamma.copy()

In [17]:
final_res = res.get_copy().child
print(final_res.child)
print(final_res.min_vals)
print(final_res.max_vals)

[[0.5808899  0.6610832  0.84622848 0.98620149 0.16347447]
 [0.83961905 0.19573528 0.85469873 0.67341633 0.27540538]
 [0.72422293 0.35704406 0.94523301 0.48327048 0.80650038]
 [0.10703216 0.00424864 0.92663971 0.52008441 0.50657996]
 [0.88296833 0.90654247 0.48253977 0.09829327 0.4685918 ]]
<lazyrepeatarray data: [0] -> shape: (5, 5)>
<lazyrepeatarray data: [1] -> shape: (5, 5)>
